//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatX.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormatX.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background canceled.
        /// </summary>
        public static string background_set_cancel {
            get {
                return ResourceManager.GetString("background.set.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set background.
        /// </summary>
        public static string background_set_error {
            get {
                return ResourceManager.GetString("background.set.error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background set.
        /// </summary>
        public static string background_set_success {
            get {
                return ResourceManager.GetString("background.set.success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string common_apply {
            get {
                return ResourceManager.GetString("common.apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string common_browse {
            get {
                return ResourceManager.GetString("common.browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export log (CSV).
        /// </summary>
        public static string common_exportCsv {
            get {
                return ResourceManager.GetString("common.exportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string common_validate {
            get {
                return ResourceManager.GetString("common.validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to proceed?.
        /// </summary>
        public static string dialog_confirm_content {
            get {
                return ResourceManager.GetString("dialog.confirm.content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string dialog_confirm_no {
            get {
                return ResourceManager.GetString("dialog.confirm.no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string dialog_confirm_title {
            get {
                return ResourceManager.GetString("dialog.confirm.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string dialog_confirm_yes {
            get {
                return ResourceManager.GetString("dialog.confirm.yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ISO.
        /// </summary>
        public static string iso_placeholder {
            get {
                return ResourceManager.GetString("iso.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        public static string menu_drives {
            get {
                return ResourceManager.GetString("menu.drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Erase.
        /// </summary>
        public static string menu_erase {
            get {
                return ResourceManager.GetString("menu.erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string menu_format {
            get {
                return ResourceManager.GetString("menu.format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string menu_settings {
            get {
                return ResourceManager.GetString("menu.settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase done.
        /// </summary>
        public static string operation_erase_done {
            get {
                return ResourceManager.GetString("operation.erase.done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format done.
        /// </summary>
        public static string operation_format_done {
            get {
                return ResourceManager.GetString("operation.format.done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition plan applied.
        /// </summary>
        public static string partitions_apply_done {
            get {
                return ResourceManager.GetString("partitions.apply.done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback applied.
        /// </summary>
        public static string partitions_rollback_applied {
            get {
                return ResourceManager.GetString("partitions.rollback.applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rollback snapshot.
        /// </summary>
        public static string partitions_rollback_none {
            get {
                return ResourceManager.GetString("partitions.rollback.none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature requires full desktop capabilities and is unavailable in S-mode..
        /// </summary>
        public static string s_mode_block {
            get {
                return ResourceManager.GetString("s.mode.block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string settings_about {
            get {
                return ResourceManager.GetString("settings.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background (JPG/PNG/BMP).
        /// </summary>
        public static string settings_background {
            get {
                return ResourceManager.GetString("settings.background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a built-in image or your own file..
        /// </summary>
        public static string settings_bg_hint {
            get {
                return ResourceManager.GetString("settings.bg.hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string settings_language {
            get {
                return ResourceManager.GetString("settings.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string settings_theme {
            get {
                return ResourceManager.GetString("settings.theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System (Default).
        /// </summary>
        public static string settings_theme_default {
            get {
                return ResourceManager.GetString("settings.theme.default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: 2.0.
        /// </summary>
        public static string settings_version {
            get {
                return ResourceManager.GetString("settings.version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string status_ready {
            get {
                return ResourceManager.GetString("status.ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected drive is a system drive (disabled)..
        /// </summary>
        public static string systemdrive_blocked {
            get {
                return ResourceManager.GetString("systemdrive.blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormatX Pro | Version: 2.0.
        /// </summary>
        public static string title_app {
            get {
                return ResourceManager.GetString("title.app", resourceCulture);
            }
        }
    }
}
