name: Lighthouse CI

on:
  pull_request:
    branches: [ master, main ]
    paths:
      - 'docs/scifi-ui/**'
      - 'lighthouserc.json'
  push:
    branches: [ master, main ]
    paths:
      - 'docs/scifi-ui/**'
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install -g @lhci/cli@0.13.x

      - name: Run Lighthouse CI
        run: |
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 30

      - name: GitHub Pages Configuration Info
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        run: |
          echo "::notice::GitHub Pages should be configured to serve from /docs folder"
          echo "::notice::Demo URL: https://hutoczky.github.io/FormatX/scifi-ui/"
          echo "::notice::Root redirect: https://hutoczky.github.io/FormatX/ → scifi-ui/"
          echo ""
          echo "To configure GitHub Pages:"
          echo "1. Go to repository Settings → Pages"
          echo "2. Set Source to 'Deploy from a branch'"
          echo "3. Select branch 'main' (or 'master') and folder '/docs'"
          echo "4. Click Save"

