name: Lighthouse CI

on:
  pull_request:
    branches: [ master, main ]
    paths:
      - 'docs/scifi-ui/**'
  push:
    branches: [ master, main ]
    paths:
      - 'docs/scifi-ui/**'
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install -g @lhci/cli@0.13.x

      - name: Run Lighthouse CI
        id: lighthouse
        run: |
          lhci autorun --rc=lighthouserc.json
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 30

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const resultsPath = '.lighthouseci';
            let comment = '## 🏠 Lighthouse CI Results\n\n';
            comment += '✅ All Lighthouse checks passed!\n\n';
            comment += '### Thresholds\n';
            comment += '- LCP < 2.5s\n';
            comment += '- CLS < 0.10\n';
            comment += '- TTFB < 600ms\n\n';
            comment += '📊 Full results uploaded as artifacts.\n\n';
            comment += '🌐 **GitHub Pages**: Will be available at `https://hutoczky.github.io/FormatX/scifi-ui/` after merge to main';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Echo Pages config on merge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "================================================"
          echo "GitHub Pages Configuration"
          echo "================================================"
          echo "Source: main branch → /docs folder"
          echo "URL: https://hutoczky.github.io/FormatX/scifi-ui/"
          echo "Root redirect: /docs/index.html → scifi-ui/"
          echo "================================================"
