name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ "master" ]
    paths:
      - "docs/**"
      - ".github/workflows/static.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact (docs/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
          name: github-pages-${{ github.run_id }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-${{ github.run_id }}